# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David Barbieri
email: barbieri.davidm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my website! This is a space where I share projects I am working on as well as things I've made. 
baseurl: / # the subpath of your site, e.g. /blog
url: "http://deebss.github.io" # the base hostname & protocol for your site
twitter_username: DavidBarberry
github_username:  deebss

# Build settings
markdown: kramdown
